
# - import_playbook: playbooks/base.yml

- name: MY infrastructure
  hosts: all
  #gether_facts: no
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - common

- name: DB MySql server
  hosts: dbserver
  # gather_facts: yes
  become: yes
    # remote_user: ubuntu
  vars_files:
    - vars/main.yml
  roles:
    - name: mysql
  tags: db


- import_playbook: playbooks/wordpress.yml
