---

- name: Install python for Ansible
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python3-minimal)
  changed_when: False

- name: Install apt packages
  apt:
    # update_cache: yes
    name:
    - git
    - curl
